name: sloosh
options:
  bundleIdPrefix: com
targets:
  sloosh:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sloosh.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: "AppIcon-Cyrillic AppIcon-Glyph"
        TARGETED_DEVICE_FAMILY: 1
        MARKETING_VERSION: "1.5"
        CURRENT_PROJECT_VERSION: "890"
        INFOPLIST_KEY_CFBundleShortVersionString: "1.5"
        INFOPLIST_KEY_CFBundleVersion: "890"
        CODESIGN_ENTITLEMENTS: sloosh/sloosh.entitlements
    sources:
      - path: sloosh/Sources
      - path: sloosh/Resources
      - path: sloosh/GoogleService-Info.plist
        buildPhase: resources
    info:
      path: sloosh/Info.plist
      properties:
        CFBundleShortVersionString: "1.5"
        CFBundleVersion: "890"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSPhotoLibraryAddUsageDescription: "Sloosh сохранит постер или логотип фильма в вашу Медиатеку."
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.sloosh.ios
            CFBundleURLSchemes:
              - sloosh
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.sloosh.ios.google
            CFBundleURLSchemes:
              - com.googleusercontent.apps.535135371915-8iou4igr3g5rfan904mtolv5r5uatfuv
