name: sloosh
options:
  bundleIdPrefix: com
targets:
  sloosh:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sloosh.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: 1
        MARKETING_VERSION: "1.1"
        CURRENT_PROJECT_VERSION: "2"
        INFOPLIST_KEY_CFBundleShortVersionString: "1.1"
        INFOPLIST_KEY_CFBundleVersion: "2"
    sources:
      - path: sloosh/Sources
      - path: sloosh/Resources
    info:
      path: sloosh/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
