name: sloosh
options:
  bundleIdPrefix: com
targets:
  sloosh:
    type: application
    platform: iOS
    deploymentTarget: "18.0" # Max target supported by current GitHub Actions Runner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sloosh.ios
    sources:
      - path: sloosh/Sources
      - path: sloosh/Resources
    info:
      path: sloosh/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
